
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `brawstats`=NULL, 
    `type`="software", 
    `author`="Watt, R. & Collins E.", 
    `year`=2019, 
    `title`="BrawStats: Psychology Research Simulation", 
    `publisher`="[SHiny App]. Retrieved from https://CRAN.R-project.org/package=emmeans", 
    `url`="https://doingpsychstats.wordpress.com/resources/brawstats-software")
