
# This file is automatically generated, you probably don't want to edit this

BrawSimOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawSimOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            DVname = "DV",
            DVtype = "Interval",
            DVmu = 0,
            DVsd = 1,
            DVskew = 0,
            DVkurt = 3,
            DVnlevs = 7,
            DViqr = 4,
            DVncats = 2,
            DVprops = "1,1",
            IVname = "IV",
            IVtype = "Interval",
            IVmu = 0,
            IVsd = 1,
            IVskew = 0,
            IVkurt = 3,
            IVnlevs = 7,
            IViqr = 4,
            IVncats = 2,
            IVprops = "1,1",
            IV2on = NULL,
            IV2name = "IV2",
            IV2type = "Interval",
            IV2mu = 0,
            IV2sd = 1,
            IV2skew = 0,
            IV2kurt = 3,
            IV2nlevs = 7,
            IV2iqr = 4,
            IV2ncats = 2,
            IV2props = "1,1",
            EffectSize1 = 0.3,
            EffectSize2 = 0.3,
            EffectSize3 = 0.3,
            EffectSize12 = 0.3,
            SampleSize = 42,
            SampleMethod = "Random",
            Dependence = 0,
            Outliers = 0,
            doInteraction = NULL,
            makeValues = NULL,
            numberSamples = 1,
            copyValues = NULL,
            appendValues = NULL,
            show = "Describe",
            showDetail = "Basic", ...) {

            super$initialize(
                package="BrawStats",
                name="BrawSim",
                requiresData=FALSE,
                ...)

            private$..DVname <- jmvcore::OptionString$new(
                "DVname",
                DVname,
                default="DV")
            private$..DVtype <- jmvcore::OptionList$new(
                "DVtype",
                DVtype,
                options=list(
                    "Interval",
                    "Ordinal",
                    "Categorical"),
                default="Interval")
            private$..DVmu <- jmvcore::OptionNumber$new(
                "DVmu",
                DVmu,
                default=0)
            private$..DVsd <- jmvcore::OptionNumber$new(
                "DVsd",
                DVsd,
                default=1)
            private$..DVskew <- jmvcore::OptionNumber$new(
                "DVskew",
                DVskew,
                default=0)
            private$..DVkurt <- jmvcore::OptionNumber$new(
                "DVkurt",
                DVkurt,
                default=3)
            private$..DVnlevs <- jmvcore::OptionNumber$new(
                "DVnlevs",
                DVnlevs,
                default=7)
            private$..DViqr <- jmvcore::OptionNumber$new(
                "DViqr",
                DViqr,
                default=4)
            private$..DVncats <- jmvcore::OptionNumber$new(
                "DVncats",
                DVncats,
                default=2)
            private$..DVprops <- jmvcore::OptionString$new(
                "DVprops",
                DVprops,
                default="1,1")
            private$..IVname <- jmvcore::OptionString$new(
                "IVname",
                IVname,
                default="IV")
            private$..IVtype <- jmvcore::OptionList$new(
                "IVtype",
                IVtype,
                options=list(
                    "Interval",
                    "Ordinal",
                    "Categorical"),
                default="Interval")
            private$..IVmu <- jmvcore::OptionNumber$new(
                "IVmu",
                IVmu,
                default=0)
            private$..IVsd <- jmvcore::OptionNumber$new(
                "IVsd",
                IVsd,
                default=1)
            private$..IVskew <- jmvcore::OptionNumber$new(
                "IVskew",
                IVskew,
                default=0)
            private$..IVkurt <- jmvcore::OptionNumber$new(
                "IVkurt",
                IVkurt,
                default=3)
            private$..IVnlevs <- jmvcore::OptionNumber$new(
                "IVnlevs",
                IVnlevs,
                default=7)
            private$..IViqr <- jmvcore::OptionNumber$new(
                "IViqr",
                IViqr,
                default=4)
            private$..IVncats <- jmvcore::OptionNumber$new(
                "IVncats",
                IVncats,
                default=2)
            private$..IVprops <- jmvcore::OptionString$new(
                "IVprops",
                IVprops,
                default="1,1")
            private$..IV2on <- jmvcore::OptionBool$new(
                "IV2on",
                IV2on)
            private$..IV2name <- jmvcore::OptionString$new(
                "IV2name",
                IV2name,
                default="IV2")
            private$..IV2type <- jmvcore::OptionList$new(
                "IV2type",
                IV2type,
                options=list(
                    "Interval",
                    "Ordinal",
                    "Categorical"),
                default="Interval")
            private$..IV2mu <- jmvcore::OptionNumber$new(
                "IV2mu",
                IV2mu,
                default=0)
            private$..IV2sd <- jmvcore::OptionNumber$new(
                "IV2sd",
                IV2sd,
                default=1)
            private$..IV2skew <- jmvcore::OptionNumber$new(
                "IV2skew",
                IV2skew,
                default=0)
            private$..IV2kurt <- jmvcore::OptionNumber$new(
                "IV2kurt",
                IV2kurt,
                default=3)
            private$..IV2nlevs <- jmvcore::OptionNumber$new(
                "IV2nlevs",
                IV2nlevs,
                default=7)
            private$..IV2iqr <- jmvcore::OptionNumber$new(
                "IV2iqr",
                IV2iqr,
                default=4)
            private$..IV2ncats <- jmvcore::OptionNumber$new(
                "IV2ncats",
                IV2ncats,
                default=2)
            private$..IV2props <- jmvcore::OptionString$new(
                "IV2props",
                IV2props,
                default="1,1")
            private$..EffectSize1 <- jmvcore::OptionNumber$new(
                "EffectSize1",
                EffectSize1,
                default=0.3)
            private$..EffectSize2 <- jmvcore::OptionNumber$new(
                "EffectSize2",
                EffectSize2,
                default=0.3)
            private$..EffectSize3 <- jmvcore::OptionNumber$new(
                "EffectSize3",
                EffectSize3,
                default=0.3)
            private$..EffectSize12 <- jmvcore::OptionNumber$new(
                "EffectSize12",
                EffectSize12,
                default=0.3)
            private$..SampleSize <- jmvcore::OptionNumber$new(
                "SampleSize",
                SampleSize,
                default=42)
            private$..SampleMethod <- jmvcore::OptionList$new(
                "SampleMethod",
                SampleMethod,
                options=list(
                    "Random",
                    "Stratified",
                    "Cluster",
                    "Convenience"),
                default="Random")
            private$..Dependence <- jmvcore::OptionNumber$new(
                "Dependence",
                Dependence,
                default=0)
            private$..Outliers <- jmvcore::OptionNumber$new(
                "Outliers",
                Outliers,
                default=0)
            private$..doInteraction <- jmvcore::OptionBool$new(
                "doInteraction",
                doInteraction)
            private$..makeValues <- jmvcore::OptionBool$new(
                "makeValues",
                makeValues)
            private$..numberSamples <- jmvcore::OptionNumber$new(
                "numberSamples",
                numberSamples,
                default=1)
            private$..copyValues <- jmvcore::OptionBool$new(
                "copyValues",
                copyValues)
            private$..appendValues <- jmvcore::OptionBool$new(
                "appendValues",
                appendValues)
            private$..sendValues <- jmvcore::OptionOutput$new(
                "sendValues")
            private$..show <- jmvcore::OptionList$new(
                "show",
                show,
                options=list(
                    "Hypothesis",
                    "Design",
                    "Population",
                    "Prediction",
                    "Sample",
                    "Describe",
                    "Infer"),
                default="Describe")
            private$..showDetail <- jmvcore::OptionList$new(
                "showDetail",
                showDetail,
                options=list(
                    "Basic",
                    "2D",
                    "r",
                    "p"),
                default="Basic")

            self$.addOption(private$..DVname)
            self$.addOption(private$..DVtype)
            self$.addOption(private$..DVmu)
            self$.addOption(private$..DVsd)
            self$.addOption(private$..DVskew)
            self$.addOption(private$..DVkurt)
            self$.addOption(private$..DVnlevs)
            self$.addOption(private$..DViqr)
            self$.addOption(private$..DVncats)
            self$.addOption(private$..DVprops)
            self$.addOption(private$..IVname)
            self$.addOption(private$..IVtype)
            self$.addOption(private$..IVmu)
            self$.addOption(private$..IVsd)
            self$.addOption(private$..IVskew)
            self$.addOption(private$..IVkurt)
            self$.addOption(private$..IVnlevs)
            self$.addOption(private$..IViqr)
            self$.addOption(private$..IVncats)
            self$.addOption(private$..IVprops)
            self$.addOption(private$..IV2on)
            self$.addOption(private$..IV2name)
            self$.addOption(private$..IV2type)
            self$.addOption(private$..IV2mu)
            self$.addOption(private$..IV2sd)
            self$.addOption(private$..IV2skew)
            self$.addOption(private$..IV2kurt)
            self$.addOption(private$..IV2nlevs)
            self$.addOption(private$..IV2iqr)
            self$.addOption(private$..IV2ncats)
            self$.addOption(private$..IV2props)
            self$.addOption(private$..EffectSize1)
            self$.addOption(private$..EffectSize2)
            self$.addOption(private$..EffectSize3)
            self$.addOption(private$..EffectSize12)
            self$.addOption(private$..SampleSize)
            self$.addOption(private$..SampleMethod)
            self$.addOption(private$..Dependence)
            self$.addOption(private$..Outliers)
            self$.addOption(private$..doInteraction)
            self$.addOption(private$..makeValues)
            self$.addOption(private$..numberSamples)
            self$.addOption(private$..copyValues)
            self$.addOption(private$..appendValues)
            self$.addOption(private$..sendValues)
            self$.addOption(private$..show)
            self$.addOption(private$..showDetail)
        }),
    active = list(
        DVname = function() private$..DVname$value,
        DVtype = function() private$..DVtype$value,
        DVmu = function() private$..DVmu$value,
        DVsd = function() private$..DVsd$value,
        DVskew = function() private$..DVskew$value,
        DVkurt = function() private$..DVkurt$value,
        DVnlevs = function() private$..DVnlevs$value,
        DViqr = function() private$..DViqr$value,
        DVncats = function() private$..DVncats$value,
        DVprops = function() private$..DVprops$value,
        IVname = function() private$..IVname$value,
        IVtype = function() private$..IVtype$value,
        IVmu = function() private$..IVmu$value,
        IVsd = function() private$..IVsd$value,
        IVskew = function() private$..IVskew$value,
        IVkurt = function() private$..IVkurt$value,
        IVnlevs = function() private$..IVnlevs$value,
        IViqr = function() private$..IViqr$value,
        IVncats = function() private$..IVncats$value,
        IVprops = function() private$..IVprops$value,
        IV2on = function() private$..IV2on$value,
        IV2name = function() private$..IV2name$value,
        IV2type = function() private$..IV2type$value,
        IV2mu = function() private$..IV2mu$value,
        IV2sd = function() private$..IV2sd$value,
        IV2skew = function() private$..IV2skew$value,
        IV2kurt = function() private$..IV2kurt$value,
        IV2nlevs = function() private$..IV2nlevs$value,
        IV2iqr = function() private$..IV2iqr$value,
        IV2ncats = function() private$..IV2ncats$value,
        IV2props = function() private$..IV2props$value,
        EffectSize1 = function() private$..EffectSize1$value,
        EffectSize2 = function() private$..EffectSize2$value,
        EffectSize3 = function() private$..EffectSize3$value,
        EffectSize12 = function() private$..EffectSize12$value,
        SampleSize = function() private$..SampleSize$value,
        SampleMethod = function() private$..SampleMethod$value,
        Dependence = function() private$..Dependence$value,
        Outliers = function() private$..Outliers$value,
        doInteraction = function() private$..doInteraction$value,
        makeValues = function() private$..makeValues$value,
        numberSamples = function() private$..numberSamples$value,
        copyValues = function() private$..copyValues$value,
        appendValues = function() private$..appendValues$value,
        sendValues = function() private$..sendValues$value,
        show = function() private$..show$value,
        showDetail = function() private$..showDetail$value),
    private = list(
        ..DVname = NA,
        ..DVtype = NA,
        ..DVmu = NA,
        ..DVsd = NA,
        ..DVskew = NA,
        ..DVkurt = NA,
        ..DVnlevs = NA,
        ..DViqr = NA,
        ..DVncats = NA,
        ..DVprops = NA,
        ..IVname = NA,
        ..IVtype = NA,
        ..IVmu = NA,
        ..IVsd = NA,
        ..IVskew = NA,
        ..IVkurt = NA,
        ..IVnlevs = NA,
        ..IViqr = NA,
        ..IVncats = NA,
        ..IVprops = NA,
        ..IV2on = NA,
        ..IV2name = NA,
        ..IV2type = NA,
        ..IV2mu = NA,
        ..IV2sd = NA,
        ..IV2skew = NA,
        ..IV2kurt = NA,
        ..IV2nlevs = NA,
        ..IV2iqr = NA,
        ..IV2ncats = NA,
        ..IV2props = NA,
        ..EffectSize1 = NA,
        ..EffectSize2 = NA,
        ..EffectSize3 = NA,
        ..EffectSize12 = NA,
        ..SampleSize = NA,
        ..SampleMethod = NA,
        ..Dependence = NA,
        ..Outliers = NA,
        ..doInteraction = NA,
        ..makeValues = NA,
        ..numberSamples = NA,
        ..copyValues = NA,
        ..appendValues = NA,
        ..sendValues = NA,
        ..show = NA,
        ..showDetail = NA)
)

BrawSimResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawSimResults",
    inherit = jmvcore::Group,
    active = list(
        graphPlot = function() private$.items[["graphPlot"]],
        graphPlot1 = function() private$.items[["graphPlot1"]],
        graphPlot2 = function() private$.items[["graphPlot2"]],
        graphPlot3 = function() private$.items[["graphPlot3"]],
        reportPlot = function() private$.items[["reportPlot"]],
        debug = function() private$.items[["debug"]],
        sendValues = function() private$.items[["sendValues"]],
        tableStore = function() private$.items[["tableStore"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="BrawStats:Simulate Data",
                refs="brawstats")
            self$add(jmvcore::Image$new(
                options=options,
                name="graphPlot",
                title=" ",
                width=500,
                height=300,
                visible=FALSE,
                refs="brawstats",
                renderFun=".plotGraph",
                clearWith=list(
                    "show",
                    "makeValues")))
            self$add(jmvcore::Image$new(
                options=options,
                name="graphPlot1",
                title=" ",
                width=250,
                height=150,
                visible=FALSE,
                renderFun=".plotGraph",
                clearWith=list(
                    "DVname",
                    "DVtype",
                    "DVmu",
                    "DVsd",
                    "DVskew",
                    "DVkurt",
                    "DVnlevs",
                    "DViqr",
                    "DVncats",
                    "DVprops",
                    "IVname",
                    "IVtype",
                    "IVmu",
                    "IVsd",
                    "IVskew",
                    "IVkurt",
                    "IVnlevs",
                    "IViqr",
                    "IVncats",
                    "IVprops",
                    "IV2on",
                    "IV2name",
                    "IV2type",
                    "IV2mu",
                    "IV2sd",
                    "IV2skew",
                    "IV2kurt",
                    "IV2nlevs",
                    "IV2iqr",
                    "IV2ncats",
                    "IV2props",
                    "EffectSize1",
                    "EffectSize2",
                    "EffectSize3",
                    "EffectSize12",
                    "SampleSize",
                    "SampleMethod",
                    "Outliers",
                    "Dependence",
                    "doInteraction",
                    "makeValues",
                    "show")))
            self$add(jmvcore::Image$new(
                options=options,
                name="graphPlot2",
                title=" ",
                width=250,
                height=150,
                visible=FALSE,
                renderFun=".plotGraph",
                clearWith=list(
                    "DVname",
                    "DVtype",
                    "DVmu",
                    "DVsd",
                    "DVskew",
                    "DVkurt",
                    "DVnlevs",
                    "DViqr",
                    "DVncats",
                    "DVprops",
                    "IVname",
                    "IVtype",
                    "IVmu",
                    "IVsd",
                    "IVskew",
                    "IVkurt",
                    "IVnlevs",
                    "IViqr",
                    "IVncats",
                    "IVprops",
                    "IV2on",
                    "IV2name",
                    "IV2type",
                    "IV2mu",
                    "IV2sd",
                    "IV2skew",
                    "IV2kurt",
                    "IV2nlevs",
                    "IV2iqr",
                    "IV2ncats",
                    "IV2props",
                    "EffectSize1",
                    "EffectSize2",
                    "EffectSize3",
                    "EffectSize12",
                    "SampleSize",
                    "SampleMethod",
                    "Outliers",
                    "Dependence",
                    "doInteraction",
                    "makeValues",
                    "show")))
            self$add(jmvcore::Image$new(
                options=options,
                name="graphPlot3",
                title=" ",
                width=250,
                height=150,
                visible=FALSE,
                renderFun=".plotGraph",
                clearWith=list(
                    "DVname",
                    "DVtype",
                    "DVmu",
                    "DVsd",
                    "DVskew",
                    "DVkurt",
                    "DVnlevs",
                    "DViqr",
                    "DVncats",
                    "DVprops",
                    "IVname",
                    "IVtype",
                    "IVmu",
                    "IVsd",
                    "IVskew",
                    "IVkurt",
                    "IVnlevs",
                    "IViqr",
                    "IVncats",
                    "IVprops",
                    "IV2on",
                    "IV2name",
                    "IV2type",
                    "IV2mu",
                    "IV2sd",
                    "IV2skew",
                    "IV2kurt",
                    "IV2nlevs",
                    "IV2iqr",
                    "IV2ncats",
                    "IV2props",
                    "EffectSize1",
                    "EffectSize2",
                    "EffectSize3",
                    "EffectSize12",
                    "SampleSize",
                    "SampleMethod",
                    "Outliers",
                    "Dependence",
                    "doInteraction",
                    "makeValues",
                    "show")))
            self$add(jmvcore::Image$new(
                options=options,
                name="reportPlot",
                title=" ",
                width=500,
                height=200,
                visible=FALSE,
                refs=list(
                    "brawstats",
                    "book"),
                renderFun=".plotReport",
                clearWith=list(
                    "makeValues",
                    "show")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="debug",
                visible=FALSE,
                clearWith=NULL))
            self$add(jmvcore::Output$new(
                options=options,
                name="sendValues",
                measureType="nominal",
                varTitle="Braw"))
            self$add(jmvcore::Table$new(
                options=options,
                name="tableStore",
                title=" ",
                visible=FALSE,
                rows=1,
                columns=list(
                    list(
                        `name`="participant", 
                        `type`="number"),
                    list(
                        `name`="iv", 
                        `type`="number"),
                    list(
                        `name`="iv2", 
                        `type`="number"),
                    list(
                        `name`="dv", 
                        `type`="number"),
                    list(
                        `name`="ivplot", 
                        `type`="number"),
                    list(
                        `name`="iv2plot", 
                        `type`="number"),
                    list(
                        `name`="dvplot", 
                        `type`="number")),
                clearWith=NULL))}))

BrawSimBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawSimBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BrawStats",
                name = "BrawSim",
                version = c(1,0,0),
                options = options,
                results = BrawSimResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' BrawStats:Simulate Data
#'
#' 
#' @param DVname .
#' @param DVtype .
#' @param DVmu .
#' @param DVsd .
#' @param DVskew .
#' @param DVkurt .
#' @param DVnlevs .
#' @param DViqr .
#' @param DVncats .
#' @param DVprops .
#' @param IVname .
#' @param IVtype .
#' @param IVmu .
#' @param IVsd .
#' @param IVskew .
#' @param IVkurt .
#' @param IVnlevs .
#' @param IViqr .
#' @param IVncats .
#' @param IVprops .
#' @param IV2on .
#' @param IV2name .
#' @param IV2type .
#' @param IV2mu .
#' @param IV2sd .
#' @param IV2skew .
#' @param IV2kurt .
#' @param IV2nlevs .
#' @param IV2iqr .
#' @param IV2ncats .
#' @param IV2props .
#' @param EffectSize1 .
#' @param EffectSize2 .
#' @param EffectSize3 .
#' @param EffectSize12 .
#' @param SampleSize .
#' @param SampleMethod .
#' @param Dependence .
#' @param Outliers .
#' @param doInteraction .
#' @param makeValues .
#' @param numberSamples .
#' @param copyValues .
#' @param appendValues .
#' @param show .
#' @param showDetail .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$graphPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$graphPlot1} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$graphPlot2} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$graphPlot3} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$reportPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$debug} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$sendValues} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$tableStore} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$tableStore$asDF}
#'
#' \code{as.data.frame(results$tableStore)}
#'
#' @export
BrawSim <- function(
    DVname = "DV",
    DVtype = "Interval",
    DVmu = 0,
    DVsd = 1,
    DVskew = 0,
    DVkurt = 3,
    DVnlevs = 7,
    DViqr = 4,
    DVncats = 2,
    DVprops = "1,1",
    IVname = "IV",
    IVtype = "Interval",
    IVmu = 0,
    IVsd = 1,
    IVskew = 0,
    IVkurt = 3,
    IVnlevs = 7,
    IViqr = 4,
    IVncats = 2,
    IVprops = "1,1",
    IV2on,
    IV2name = "IV2",
    IV2type = "Interval",
    IV2mu = 0,
    IV2sd = 1,
    IV2skew = 0,
    IV2kurt = 3,
    IV2nlevs = 7,
    IV2iqr = 4,
    IV2ncats = 2,
    IV2props = "1,1",
    EffectSize1 = 0.3,
    EffectSize2 = 0.3,
    EffectSize3 = 0.3,
    EffectSize12 = 0.3,
    SampleSize = 42,
    SampleMethod = "Random",
    Dependence = 0,
    Outliers = 0,
    doInteraction,
    makeValues,
    numberSamples = 1,
    copyValues,
    appendValues,
    show = "Describe",
    showDetail = "Basic") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("BrawSim requires jmvcore to be installed (restart may be required)")


    options <- BrawSimOptions$new(
        DVname = DVname,
        DVtype = DVtype,
        DVmu = DVmu,
        DVsd = DVsd,
        DVskew = DVskew,
        DVkurt = DVkurt,
        DVnlevs = DVnlevs,
        DViqr = DViqr,
        DVncats = DVncats,
        DVprops = DVprops,
        IVname = IVname,
        IVtype = IVtype,
        IVmu = IVmu,
        IVsd = IVsd,
        IVskew = IVskew,
        IVkurt = IVkurt,
        IVnlevs = IVnlevs,
        IViqr = IViqr,
        IVncats = IVncats,
        IVprops = IVprops,
        IV2on = IV2on,
        IV2name = IV2name,
        IV2type = IV2type,
        IV2mu = IV2mu,
        IV2sd = IV2sd,
        IV2skew = IV2skew,
        IV2kurt = IV2kurt,
        IV2nlevs = IV2nlevs,
        IV2iqr = IV2iqr,
        IV2ncats = IV2ncats,
        IV2props = IV2props,
        EffectSize1 = EffectSize1,
        EffectSize2 = EffectSize2,
        EffectSize3 = EffectSize3,
        EffectSize12 = EffectSize12,
        SampleSize = SampleSize,
        SampleMethod = SampleMethod,
        Dependence = Dependence,
        Outliers = Outliers,
        doInteraction = doInteraction,
        makeValues = makeValues,
        numberSamples = numberSamples,
        copyValues = copyValues,
        appendValues = appendValues,
        show = show,
        showDetail = showDetail)

    analysis <- BrawSimClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

