
# This file is automatically generated, you probably don't want to edit this

BrawSimOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawSimOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            DVname = "DV",
            DVtype = "Interval",
            DVmu = 0,
            DVsd = 1,
            DVskew = 0,
            DVkurt = 3,
            IVname = "IV",
            IVtype = "Interval",
            IVmu = 0,
            IVsd = 1,
            IVskew = 0,
            IVkurt = 3,
            IV2on = NULL,
            IV2name = "IV2",
            IV2type = "Interval",
            IV2mu = 0,
            IV2sd = 1,
            IV2skew = 0,
            IV2kurt = 3,
            EffectSize1 = 0.3,
            EffectSize2 = 0.3,
            EffectSize3 = 0.3,
            EffectSize12 = 0.3,
            SampleSize = 42,
            SampleMethod = "Random",
            Dependence = 0,
            Outliers = 0,
            copyValues = NULL,
            makeValues = NULL,
            doInteraction = NULL,
            show = "Sample",
            inferWhich = "2D", ...) {

            super$initialize(
                package="BrawStats",
                name="BrawSim",
                requiresData=FALSE,
                ...)

            private$..DVname <- jmvcore::OptionString$new(
                "DVname",
                DVname,
                default="DV")
            private$..DVtype <- jmvcore::OptionList$new(
                "DVtype",
                DVtype,
                options=list(
                    "Interval",
                    "Ordinal",
                    "Categorical"),
                default="Interval")
            private$..DVmu <- jmvcore::OptionNumber$new(
                "DVmu",
                DVmu,
                default=0)
            private$..DVsd <- jmvcore::OptionNumber$new(
                "DVsd",
                DVsd,
                default=1)
            private$..DVskew <- jmvcore::OptionNumber$new(
                "DVskew",
                DVskew,
                default=0)
            private$..DVkurt <- jmvcore::OptionNumber$new(
                "DVkurt",
                DVkurt,
                default=3)
            private$..IVname <- jmvcore::OptionString$new(
                "IVname",
                IVname,
                default="IV")
            private$..IVtype <- jmvcore::OptionList$new(
                "IVtype",
                IVtype,
                options=list(
                    "Interval",
                    "Ordinal",
                    "Categorical"),
                default="Interval")
            private$..IVmu <- jmvcore::OptionNumber$new(
                "IVmu",
                IVmu,
                default=0)
            private$..IVsd <- jmvcore::OptionNumber$new(
                "IVsd",
                IVsd,
                default=1)
            private$..IVskew <- jmvcore::OptionNumber$new(
                "IVskew",
                IVskew,
                default=0)
            private$..IVkurt <- jmvcore::OptionNumber$new(
                "IVkurt",
                IVkurt,
                default=3)
            private$..IV2on <- jmvcore::OptionBool$new(
                "IV2on",
                IV2on)
            private$..IV2name <- jmvcore::OptionString$new(
                "IV2name",
                IV2name,
                default="IV2")
            private$..IV2type <- jmvcore::OptionList$new(
                "IV2type",
                IV2type,
                options=list(
                    "Interval",
                    "Ordinal",
                    "Categorical"),
                default="Interval")
            private$..IV2mu <- jmvcore::OptionNumber$new(
                "IV2mu",
                IV2mu,
                default=0)
            private$..IV2sd <- jmvcore::OptionNumber$new(
                "IV2sd",
                IV2sd,
                default=1)
            private$..IV2skew <- jmvcore::OptionNumber$new(
                "IV2skew",
                IV2skew,
                default=0)
            private$..IV2kurt <- jmvcore::OptionNumber$new(
                "IV2kurt",
                IV2kurt,
                default=3)
            private$..EffectSize1 <- jmvcore::OptionNumber$new(
                "EffectSize1",
                EffectSize1,
                default=0.3)
            private$..EffectSize2 <- jmvcore::OptionNumber$new(
                "EffectSize2",
                EffectSize2,
                default=0.3)
            private$..EffectSize3 <- jmvcore::OptionNumber$new(
                "EffectSize3",
                EffectSize3,
                default=0.3)
            private$..EffectSize12 <- jmvcore::OptionNumber$new(
                "EffectSize12",
                EffectSize12,
                default=0.3)
            private$..SampleSize <- jmvcore::OptionNumber$new(
                "SampleSize",
                SampleSize,
                default=42)
            private$..SampleMethod <- jmvcore::OptionList$new(
                "SampleMethod",
                SampleMethod,
                options=list(
                    "Random",
                    "Stratified",
                    "Cluster",
                    "Convenience"),
                default="Random")
            private$..Dependence <- jmvcore::OptionNumber$new(
                "Dependence",
                Dependence,
                default=0)
            private$..Outliers <- jmvcore::OptionNumber$new(
                "Outliers",
                Outliers,
                default=0)
            private$..copyValues <- jmvcore::OptionBool$new(
                "copyValues",
                copyValues)
            private$..makeValues <- jmvcore::OptionBool$new(
                "makeValues",
                makeValues)
            private$..doInteraction <- jmvcore::OptionBool$new(
                "doInteraction",
                doInteraction)
            private$..show <- jmvcore::OptionList$new(
                "show",
                show,
                options=list(
                    "Sample",
                    "Describe",
                    "Infer"),
                default="Sample")
            private$..inferWhich <- jmvcore::OptionList$new(
                "inferWhich",
                inferWhich,
                options=list(
                    "r",
                    "p",
                    "2D"),
                default="2D")
            private$..sendValues <- jmvcore::OptionOutput$new(
                "sendValues")

            self$.addOption(private$..DVname)
            self$.addOption(private$..DVtype)
            self$.addOption(private$..DVmu)
            self$.addOption(private$..DVsd)
            self$.addOption(private$..DVskew)
            self$.addOption(private$..DVkurt)
            self$.addOption(private$..IVname)
            self$.addOption(private$..IVtype)
            self$.addOption(private$..IVmu)
            self$.addOption(private$..IVsd)
            self$.addOption(private$..IVskew)
            self$.addOption(private$..IVkurt)
            self$.addOption(private$..IV2on)
            self$.addOption(private$..IV2name)
            self$.addOption(private$..IV2type)
            self$.addOption(private$..IV2mu)
            self$.addOption(private$..IV2sd)
            self$.addOption(private$..IV2skew)
            self$.addOption(private$..IV2kurt)
            self$.addOption(private$..EffectSize1)
            self$.addOption(private$..EffectSize2)
            self$.addOption(private$..EffectSize3)
            self$.addOption(private$..EffectSize12)
            self$.addOption(private$..SampleSize)
            self$.addOption(private$..SampleMethod)
            self$.addOption(private$..Dependence)
            self$.addOption(private$..Outliers)
            self$.addOption(private$..copyValues)
            self$.addOption(private$..makeValues)
            self$.addOption(private$..doInteraction)
            self$.addOption(private$..show)
            self$.addOption(private$..inferWhich)
            self$.addOption(private$..sendValues)
        }),
    active = list(
        DVname = function() private$..DVname$value,
        DVtype = function() private$..DVtype$value,
        DVmu = function() private$..DVmu$value,
        DVsd = function() private$..DVsd$value,
        DVskew = function() private$..DVskew$value,
        DVkurt = function() private$..DVkurt$value,
        IVname = function() private$..IVname$value,
        IVtype = function() private$..IVtype$value,
        IVmu = function() private$..IVmu$value,
        IVsd = function() private$..IVsd$value,
        IVskew = function() private$..IVskew$value,
        IVkurt = function() private$..IVkurt$value,
        IV2on = function() private$..IV2on$value,
        IV2name = function() private$..IV2name$value,
        IV2type = function() private$..IV2type$value,
        IV2mu = function() private$..IV2mu$value,
        IV2sd = function() private$..IV2sd$value,
        IV2skew = function() private$..IV2skew$value,
        IV2kurt = function() private$..IV2kurt$value,
        EffectSize1 = function() private$..EffectSize1$value,
        EffectSize2 = function() private$..EffectSize2$value,
        EffectSize3 = function() private$..EffectSize3$value,
        EffectSize12 = function() private$..EffectSize12$value,
        SampleSize = function() private$..SampleSize$value,
        SampleMethod = function() private$..SampleMethod$value,
        Dependence = function() private$..Dependence$value,
        Outliers = function() private$..Outliers$value,
        copyValues = function() private$..copyValues$value,
        makeValues = function() private$..makeValues$value,
        doInteraction = function() private$..doInteraction$value,
        show = function() private$..show$value,
        inferWhich = function() private$..inferWhich$value,
        sendValues = function() private$..sendValues$value),
    private = list(
        ..DVname = NA,
        ..DVtype = NA,
        ..DVmu = NA,
        ..DVsd = NA,
        ..DVskew = NA,
        ..DVkurt = NA,
        ..IVname = NA,
        ..IVtype = NA,
        ..IVmu = NA,
        ..IVsd = NA,
        ..IVskew = NA,
        ..IVkurt = NA,
        ..IV2on = NA,
        ..IV2name = NA,
        ..IV2type = NA,
        ..IV2mu = NA,
        ..IV2sd = NA,
        ..IV2skew = NA,
        ..IV2kurt = NA,
        ..EffectSize1 = NA,
        ..EffectSize2 = NA,
        ..EffectSize3 = NA,
        ..EffectSize12 = NA,
        ..SampleSize = NA,
        ..SampleMethod = NA,
        ..Dependence = NA,
        ..Outliers = NA,
        ..copyValues = NA,
        ..makeValues = NA,
        ..doInteraction = NA,
        ..show = NA,
        ..inferWhich = NA,
        ..sendValues = NA)
)

BrawSimResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawSimResults",
    inherit = jmvcore::Group,
    active = list(
        graphPlot = function() private$.items[["graphPlot"]],
        reportPlot = function() private$.items[["reportPlot"]],
        debug = function() private$.items[["debug"]],
        sendValues = function() private$.items[["sendValues"]],
        tableStore = function() private$.items[["tableStore"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="BrawStats:Simulate Data")
            self$add(jmvcore::Image$new(
                options=options,
                name="graphPlot",
                title=" ",
                width=500,
                height=300,
                renderFun=".plotGraph"))
            self$add(jmvcore::Image$new(
                options=options,
                name="reportPlot",
                title=" ",
                width=500,
                height=200,
                renderFun=".plotReport"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="debug",
                visible=FALSE))
            self$add(jmvcore::Output$new(
                options=options,
                name="sendValues",
                measureType="nominal",
                varTitle="Braw"))
            self$add(jmvcore::Table$new(
                options=options,
                name="tableStore",
                title=" ",
                visible=FALSE,
                rows=1,
                columns=list(
                    list(
                        `name`="participant", 
                        `type`="number"),
                    list(
                        `name`="iv", 
                        `type`="number"),
                    list(
                        `name`="iv2", 
                        `type`="number"),
                    list(
                        `name`="dv", 
                        `type`="number"),
                    list(
                        `name`="ivplot", 
                        `type`="number"),
                    list(
                        `name`="iv2plot", 
                        `type`="number"),
                    list(
                        `name`="dvplot", 
                        `type`="number")),
                clearWith=NULL))}))

BrawSimBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawSimBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BrawStats",
                name = "BrawSim",
                version = c(1,0,0),
                options = options,
                results = BrawSimResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' BrawStats:Simulate Data
#'
#' 
#' @param DVname .
#' @param DVtype .
#' @param DVmu .
#' @param DVsd .
#' @param DVskew .
#' @param DVkurt .
#' @param IVname .
#' @param IVtype .
#' @param IVmu .
#' @param IVsd .
#' @param IVskew .
#' @param IVkurt .
#' @param IV2on .
#' @param IV2name .
#' @param IV2type .
#' @param IV2mu .
#' @param IV2sd .
#' @param IV2skew .
#' @param IV2kurt .
#' @param EffectSize1 .
#' @param EffectSize2 .
#' @param EffectSize3 .
#' @param EffectSize12 .
#' @param SampleSize .
#' @param SampleMethod .
#' @param Dependence .
#' @param Outliers .
#' @param copyValues .
#' @param makeValues .
#' @param doInteraction .
#' @param show .
#' @param inferWhich .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$graphPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$reportPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$debug} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$sendValues} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$tableStore} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$tableStore$asDF}
#'
#' \code{as.data.frame(results$tableStore)}
#'
#' @export
BrawSim <- function(
    DVname = "DV",
    DVtype = "Interval",
    DVmu = 0,
    DVsd = 1,
    DVskew = 0,
    DVkurt = 3,
    IVname = "IV",
    IVtype = "Interval",
    IVmu = 0,
    IVsd = 1,
    IVskew = 0,
    IVkurt = 3,
    IV2on,
    IV2name = "IV2",
    IV2type = "Interval",
    IV2mu = 0,
    IV2sd = 1,
    IV2skew = 0,
    IV2kurt = 3,
    EffectSize1 = 0.3,
    EffectSize2 = 0.3,
    EffectSize3 = 0.3,
    EffectSize12 = 0.3,
    SampleSize = 42,
    SampleMethod = "Random",
    Dependence = 0,
    Outliers = 0,
    copyValues,
    makeValues,
    doInteraction,
    show = "Sample",
    inferWhich = "2D") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("BrawSim requires jmvcore to be installed (restart may be required)")


    options <- BrawSimOptions$new(
        DVname = DVname,
        DVtype = DVtype,
        DVmu = DVmu,
        DVsd = DVsd,
        DVskew = DVskew,
        DVkurt = DVkurt,
        IVname = IVname,
        IVtype = IVtype,
        IVmu = IVmu,
        IVsd = IVsd,
        IVskew = IVskew,
        IVkurt = IVkurt,
        IV2on = IV2on,
        IV2name = IV2name,
        IV2type = IV2type,
        IV2mu = IV2mu,
        IV2sd = IV2sd,
        IV2skew = IV2skew,
        IV2kurt = IV2kurt,
        EffectSize1 = EffectSize1,
        EffectSize2 = EffectSize2,
        EffectSize3 = EffectSize3,
        EffectSize12 = EffectSize12,
        SampleSize = SampleSize,
        SampleMethod = SampleMethod,
        Dependence = Dependence,
        Outliers = Outliers,
        copyValues = copyValues,
        makeValues = makeValues,
        doInteraction = doInteraction,
        show = show,
        inferWhich = inferWhich)

    analysis <- BrawSimClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

