
# This file is automatically generated, you probably don't want to edit this

chi2rOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "chi2rOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            group1sz = 0,
            group2sz = 0,
            chisqr = 0, ...) {

            super$initialize(
                package="BrawStats",
                name="chi2r",
                requiresData=FALSE,
                ...)

            private$..group1sz <- jmvcore::OptionNumber$new(
                "group1sz",
                group1sz,
                default=0)
            private$..group2sz <- jmvcore::OptionNumber$new(
                "group2sz",
                group2sz,
                default=0)
            private$..chisqr <- jmvcore::OptionNumber$new(
                "chisqr",
                chisqr,
                default=0)

            self$.addOption(private$..group1sz)
            self$.addOption(private$..group2sz)
            self$.addOption(private$..chisqr)
        }),
    active = list(
        group1sz = function() private$..group1sz$value,
        group2sz = function() private$..group2sz$value,
        chisqr = function() private$..chisqr$value),
    private = list(
        ..group1sz = NA,
        ..group2sz = NA,
        ..chisqr = NA)
)

chi2rResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "chi2rResults",
    inherit = jmvcore::Group,
    active = list(
        chi_text = function() private$.items[["chi_text"]],
        r_text = function() private$.items[["r_text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="chisquare to r")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="chi_text",
                title=" "))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="r_text",
                title=" "))}))

chi2rBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "chi2rBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BrawStats",
                name = "chi2r",
                version = c(1,0,0),
                options = options,
                results = chi2rResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' chisquare to r
#'
#' 
#' @param group1sz .
#' @param group2sz .
#' @param chisqr .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$chi_text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$r_text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
chi2r <- function(
    group1sz = 0,
    group2sz = 0,
    chisqr = 0) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("chi2r requires jmvcore to be installed (restart may be required)")


    options <- chi2rOptions$new(
        group1sz = group1sz,
        group2sz = group2sz,
        chisqr = chisqr)

    analysis <- chi2rClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

