
# This file is automatically generated, you probably don't want to edit this

d2rOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "d2rOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            group1sz = 0,
            group1mn = 0,
            group1sd = 0,
            group2sz = 0,
            group2mn = 0,
            group2sd = 0, ...) {

            super$initialize(
                package="BrawStats",
                name="d2r",
                requiresData=FALSE,
                ...)

            private$..group1sz <- jmvcore::OptionNumber$new(
                "group1sz",
                group1sz,
                default=0)
            private$..group1mn <- jmvcore::OptionNumber$new(
                "group1mn",
                group1mn,
                default=0)
            private$..group1sd <- jmvcore::OptionNumber$new(
                "group1sd",
                group1sd,
                default=0)
            private$..group2sz <- jmvcore::OptionNumber$new(
                "group2sz",
                group2sz,
                default=0)
            private$..group2mn <- jmvcore::OptionNumber$new(
                "group2mn",
                group2mn,
                default=0)
            private$..group2sd <- jmvcore::OptionNumber$new(
                "group2sd",
                group2sd,
                default=0)

            self$.addOption(private$..group1sz)
            self$.addOption(private$..group1mn)
            self$.addOption(private$..group1sd)
            self$.addOption(private$..group2sz)
            self$.addOption(private$..group2mn)
            self$.addOption(private$..group2sd)
        }),
    active = list(
        group1sz = function() private$..group1sz$value,
        group1mn = function() private$..group1mn$value,
        group1sd = function() private$..group1sd$value,
        group2sz = function() private$..group2sz$value,
        group2mn = function() private$..group2mn$value,
        group2sd = function() private$..group2sd$value),
    private = list(
        ..group1sz = NA,
        ..group1mn = NA,
        ..group1sd = NA,
        ..group2sz = NA,
        ..group2mn = NA,
        ..group2sd = NA)
)

d2rResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "d2rResults",
    inherit = jmvcore::Group,
    active = list(
        d_text = function() private$.items[["d_text"]],
        r_text = function() private$.items[["r_text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="t-test to r")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="d_text",
                title=" "))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="r_text",
                title=" "))}))

d2rBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "d2rBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BrawStats",
                name = "d2r",
                version = c(1,0,0),
                options = options,
                results = d2rResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' t-test to r
#'
#' 
#' @param group1sz .
#' @param group1mn .
#' @param group1sd .
#' @param group2sz .
#' @param group2mn .
#' @param group2sd .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$d_text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$r_text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
d2r <- function(
    group1sz = 0,
    group1mn = 0,
    group1sd = 0,
    group2sz = 0,
    group2mn = 0,
    group2sd = 0) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("d2r requires jmvcore to be installed (restart may be required)")


    options <- d2rOptions$new(
        group1sz = group1sz,
        group1mn = group1mn,
        group1sd = group1sd,
        group2sz = group2sz,
        group2mn = group2mn,
        group2sd = group2sd)

    analysis <- d2rClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

