
# This file is automatically generated, you probably don't want to edit this

log2rOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "log2rOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rsqr = 0, ...) {

            super$initialize(
                package="BrawStats",
                name="log2r",
                requiresData=FALSE,
                ...)

            private$..rsqr <- jmvcore::OptionNumber$new(
                "rsqr",
                rsqr,
                default=0)

            self$.addOption(private$..rsqr)
        }),
    active = list(
        rsqr = function() private$..rsqr$value),
    private = list(
        ..rsqr = NA)
)

log2rResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "log2rResults",
    inherit = jmvcore::Group,
    active = list(
        reportPlot = function() private$.items[["reportPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="logistic regression to r")
            self$add(jmvcore::Image$new(
                options=options,
                name="reportPlot",
                title=" ",
                width=500,
                height=200,
                renderFun=".plotReport"))}))

log2rBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "log2rBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BrawStats",
                name = "log2r",
                version = c(1,0,0),
                options = options,
                results = log2rResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' logistic regression to r
#'
#' 
#' @param rsqr .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$reportPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
log2r <- function(
    rsqr = 0) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("log2r requires jmvcore to be installed (restart may be required)")


    options <- log2rOptions$new(
        rsqr = rsqr)

    analysis <- log2rClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

