
# This file is automatically generated, you probably don't want to edit this

BrawAnOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawAnOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            IV = NULL,
            DV = NULL,
            doInteraction = NULL,
            show = "Infer",
            inferWhich = "2D", ...) {

            super$initialize(
                package="BrawStats",
                name="BrawAn",
                requiresData=TRUE,
                ...)

            private$..IV <- jmvcore::OptionVariables$new(
                "IV",
                IV)
            private$..DV <- jmvcore::OptionVariable$new(
                "DV",
                DV)
            private$..doInteraction <- jmvcore::OptionBool$new(
                "doInteraction",
                doInteraction)
            private$..show <- jmvcore::OptionList$new(
                "show",
                show,
                options=list(
                    "Sample",
                    "Describe",
                    "Infer"),
                default="Infer")
            private$..inferWhich <- jmvcore::OptionList$new(
                "inferWhich",
                inferWhich,
                options=list(
                    "r",
                    "p",
                    "2D"),
                default="2D")

            self$.addOption(private$..IV)
            self$.addOption(private$..DV)
            self$.addOption(private$..doInteraction)
            self$.addOption(private$..show)
            self$.addOption(private$..inferWhich)
        }),
    active = list(
        IV = function() private$..IV$value,
        DV = function() private$..DV$value,
        doInteraction = function() private$..doInteraction$value,
        show = function() private$..show$value,
        inferWhich = function() private$..inferWhich$value),
    private = list(
        ..IV = NA,
        ..DV = NA,
        ..doInteraction = NA,
        ..show = NA,
        ..inferWhich = NA)
)

BrawAnResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawAnResults",
    inherit = jmvcore::Group,
    active = list(
        graphPlot = function() private$.items[["graphPlot"]],
        reportPlot = function() private$.items[["reportPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="BrawStats:Analyze Data")
            self$add(jmvcore::Image$new(
                options=options,
                name="graphPlot",
                title=" ",
                width=500,
                height=300,
                renderFun=".plotGraph"))
            self$add(jmvcore::Image$new(
                options=options,
                name="reportPlot",
                title=" ",
                width=500,
                height=200,
                renderFun=".plotReport"))}))

BrawAnBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "BrawAnBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "BrawStats",
                name = "BrawAn",
                version = c(1,0,0),
                options = options,
                results = BrawAnResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' BrawStats:Analyze Data
#'
#' 
#' @param data .
#' @param IV .
#' @param DV .
#' @param doInteraction .
#' @param show .
#' @param inferWhich .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$graphPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$reportPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
BrawAn <- function(
    data,
    IV,
    DV,
    doInteraction,
    show = "Infer",
    inferWhich = "2D") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("BrawAn requires jmvcore to be installed (restart may be required)")

    if ( ! missing(IV)) IV <- jmvcore::resolveQuo(jmvcore::enquo(IV))
    if ( ! missing(DV)) DV <- jmvcore::resolveQuo(jmvcore::enquo(DV))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(IV), IV, NULL),
            `if`( ! missing(DV), DV, NULL))


    options <- BrawAnOptions$new(
        IV = IV,
        DV = DV,
        doInteraction = doInteraction,
        show = show,
        inferWhich = inferWhich)

    analysis <- BrawAnClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

